# Generated by Django 5.0.4 on 2024-04-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poste_type',
            field=models.TextField(choices=[('offre', 'offre'), ('demande', 'demande')], default='demande'),
        ),
    ]
