# Generated by Django 5.0.4 on 2024-04-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_poste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poste_modele',
            field=models.TextField(choices=[('stage', 'stage'), ('transport', 'transport'), ('evenement', 'evenement'), ('logement', 'logement')], default='stage'),
        ),
    ]
