# Generated by Django 5.0.4 on 2024-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_logement_post_remove_stage_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poste_modele',
            field=models.TextField(blank=True, choices=[('stage', 'stage'), ('transport', 'transport'), ('evenement', 'evenement'), ('logement', 'logement')]),
        ),
    ]
