# Generated by Django 5.0.4 on 2024-04-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_poste_modele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heure_depart',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
